language: node_js
sudo: false
branches:
  only:
  - gh-pages
install:
  - npm install
env:
  global:
  - URL="http://w3c.github.io/navigation-timing/W3CTRMANIFEST"
  - DECISION="http://www.w3.org/2015/06/24-webperf-minutes.html#item01"
  - secure: "qUa2nSP80N6KZcU1FVk9JfxNlVIYGVWLpQ8Ct2ZbCusvHRQE6/qJyclylh+L8qKpbhLbeZOCsJqUJvqX4a701yGhQaWrU0WGXMKjbBJOWGl+Lu25M6wkI0KCL+2V1xfTc81kZIODKNuyQK7JKdTVNWLMt/pCl0lclC+iBiUuofY="
script:
  - curl -o linkreport.html https://validator.w3.org/checklink\?uri\=https%3A%2F%2Flabs.w3.org%2Fspec-generator%2F%3Ftype%3Drespec%26url%3Dhttps%3A%2F%2Fw3c.github.io%2Fnavigation-timing%2F\&hide_type\=all\&depth\=\&check\=Check\&summary\=on
  - node linkchecker.js
  - rm linkreport.html
  - echo "ok"
after_success:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && curl "https://labs.w3.org/echidna/api/request" --data "url=$URL" --data "decision=$DECISION"
  --data "token=$TOKEN"'

node_js:
  - v7.9
