language: node_js
sudo: false
branches:
  only:
  - gh-pages
install:
  - npm install
env:
  global:
  - ECHIDNA_URL = "https://labs.w3.org/echidna/api/request"
  - SPEC_URL="https://w3c.github.io/navigation-timing/"
  - ECHIDNA_MANIFEST_URL="$SPEC_URL/W3CTRMANIFEST"
  - DECISION_URL="http://www.w3.org/2015/06/24-webperf-minutes.html#item01"
  - SPEC_GENERATOR_URL="https://labs.w3.org/spec-generator/?type=respec"
  - LINKCHECKER_URL="https://validator.w3.org/checklink"
  - secure: "qUa2nSP80N6KZcU1FVk9JfxNlVIYGVWLpQ8Ct2ZbCusvHRQE6/qJyclylh+L8qKpbhLbeZOCsJqUJvqX4a701yGhQaWrU0WGXMKjbBJOWGl+Lu25M6wkI0KCL+2V1xfTc81kZIODKNuyQK7JKdTVNWLMt/pCl0lclC+iBiUuofY="
script:
  - curl -o linkreport.html "$LINKCHECKER_URL?uri=$SPEC_GENERATOR_URL&url=$SPEC_URL"
  - node linkchecker.js
  - rm linkreport.html
  - echo "ok"
after_success:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && curl "$ECHIDNA_URL" --data "url=$ECHIDNA_MANIFEST_URL" --data "decision=$DECISION_URL"
  --data "token=$TOKEN"'

node_js:
  - v7.9
